### PR TITLE
sorted

### PR DESCRIPTION
**Pull request by sheerluck**
I think it looks nice :)

### CODE REVIEW

**Comment by mristin** [comment]
Hi @sheerluck ,
Thanks for submission! I'll try to review it tomorrow or day after tomorrow. You might have not noticed that the tests fail. Is it OK if I make a new pull requests with the tests fixed or would you like to fix tests on your side?

**Comment by sheerluck** [comment]
I think it's OK to make a new pull request if you like the way it sorted after this patch applied, because you may end up achieving the same result in different way (without way too long lambda maybe). Or maybe drop case insensitive sort if you like case sensitive sort more.

**Comment by mristin** [comment]
Hi @sheerluck ,
After some more thinking, I came to conclusion that sorting the output is not such a good idea. Namely, there might be clear intention by the developers of `ldd` to follow a specific (non-alphabetic) order. That order depends on your platform, by pylddwrap should not mess with it.

How did you intend to use this feature actually? Would a `--sorted` flag do the trick?

**Comment by sheerluck** [comment]
`-s/--sorted` would be great

**Comment by mristin** [comment]
Implemented in a further pull request #7 .

**Pull request closed without merging**
