### PR TITLE
Retain leading tabs in test examples

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [x] CI testing (presuming CI will be added, such as in https://github.com/Parquery/pylddwrap/pull/16)
- [x] More complete CI testing from one or more other PRs (coverage, formatting, etc etc)

This looks like a nasty format-it-in-my-style PR.  I promise you that is not the intent.  `:]`  The issue is that the original use of `textwrap.dedent()` was stripping the leading tabs.  That is \_all\_ I hope to fix here.  There are certainly several other ways this could be written.  I happened to pick this way.  You are welcome to correct it, provide a separate fix, or let me know how you want it to look and I'll do the grunt work.  I'll be happy with whatever solution.

This could be argued to relate to #14 where pylddwrap would become sensitive to the indentation.  I thought it made sense as a separate PR since it fixes an existing and independent inaccuracy in the tests.

Side note, would you be interested in a GitHub Actions testing workflow?  I'd be happy to write that up for you. (edit: I just went for it https://github.com/Parquery/pylddwrap/pull/16)

### CODE REVIEW

**Comment by altendky** [comment]
Hmm, I'll mark this as draft as well in case I find more related bits to tweak.

**Comment by altendky** [comment]
FWIW, I don't like how the strings with leading tabs are written.  I considered several other options and all were gross.  If there's something you like, or dislike less, that retains the tabs...  lemme know and I'll write them that way.

**Comment by altendky** [comment]
@mristin, this one is ready for consideration as well.

**Comment by mristin** [comment]
LGTM, thanks! Should I merge?

**Comment by altendky** [comment]
Go for it.  Thanks.

**Pull request merged**
